name: Docker Image CI

on:
  push:
    branches: [ main, gha-test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get current version from package.json
      run: >
        echo "X_NEW_VERSION=$(cat < package.json | grep -Po '(?<=\"version\": \")([^\"]*)')" >> $GITHUB_ENV
    - name: Compare latest and current version
      run: if [ "$X_NEW_VERSION" != "$X_APP_VERSION" ]; then echo "X_OLD_VERSION=$X_APP_VERSION" >> "$GITHUB_ENV"; echo "X_APP_VERSION=$X_NEW_VERSION" >> "$GITHUB_ENV"; fi
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag qanary-ui:latest
    - name: Tag image with specific version
      run: if [ "$X_OLD_VERSION" != "$X_NEW_VERSION" ]; then docker tag qanary-ui:latest qanary/qanary-ui:"$X_APP_VERSION"; fi 
    - name: Tag docker image with latest version
      run: docker tag qanary-ui:latest qanary/qanary-ui:latest
    - name: Test dynamic version updates
      run: echo "new version is $X_NEW_VERSION; old version is $X_OLD_VERSION; app version is $X_APP_VERSION"
